name: daily-summaries

on:
  schedule:
    - cron: '59 22 * * *'   # 22:59 UTC ≈ 23:59 à Paris (hiver)
  workflow_dispatch:        # bouton "Run workflow" manuel

permissions:
  contents: write           # autorise le push des fichiers générés

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 1) Installer les dépendances
      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f google-alerts-summarizer/requirements.txt ]; then pip install -r google-alerts-summarizer/requirements.txt; fi
          pip install markdown

      # 2) Lancer TON script qui produit output/YYYY-MM-DD.md
      #    ⚠️ Si ton main.py est dans le dossier google-alerts-summarizer, on lance cette ligne
      - name: Run your script (produit output/*.md)
        env:
          FEEDS: "https://www.google.fr/alerts/feeds/06828307252155608763/17948382890845885017"
          SENTENCES: "4"
          MAX_PER_FEED: "50"
        run: |
          if [ -f main.py ]; then python main.py; \
          elif [ -f google-alerts-summarizer/main.py ]; then python google-alerts-summarizer/main.py; \
          else echo "main.py introuvable"; exit 1; fi

      # 3) Construire les pages HTML jolies dans docs/
      - name: Build static site (docs/)
        run: python build_site.py

      # 4) Commit + push des fichiers générés (docs/ et output/)
      - name: Commit & Push results
        run: |
          git config user.name "rss-bot"
          git config user.email "rss-bot@users.noreply.github.com"
          git add docs output
          git commit -m "site maj $(date -u +'%Y-%m-%d %H:%M')" || echo "rien à committer"
          git push
